#include <stdio.h>
#include <stdlib.h> //handle system("pause")，结束后不立即退出
#include <math.h>
#include <time.h>

#define max2 1530000000 // buffer_shrink
#define list 1000000000LL    // 结果列表
//-------------------------------------------------------------------------------------------------//
// 目标
#define Target_number (double)8.080174247945128e+53 // 8.08017424794512875815e+53 //double t;t=powl(2,46)*powl(3,20)*powl(5,9)*powl(7,6)*powl(11,2)*powl(13,3)*17*19*23*29*31*41*47*59*71;printf("%.15Le\n",t);
// 组成的常数
#define self 1 // could be generated by ^0
// Physics
#define Speed_of_light 2.99792458e8
#define Proton_length 1.754e-15 // 0.84e-15--0.87e-15/0.833e-15
#define Planck_constant 6.62607015e-34
#define Planck_constant_reduced 1.054571817646156391262428e-34
#define Planck_time 5.39116e-44
#define Planck_mass 2.176434e-8
#define Planck_length 1.616229e-35
#define Proton_mass 1.6726231e-27
#define Gravitational_constant 6.67430e-11
#define Charge 1.602176e-19
#define Vacuum_Permittivity_E0 8.854187817e-12
#define Vacuum_Permittivity_u0 1.25663706212e-6
#define Coulomb_constant_F 8.9875517923e9
#define Conductance_quantum 7.748091729e-5
#define Wien_constant 2.897771955e-3
// Chemistry
#define Boltzmann_constant 1.380649e-23
#define Stefan_Boltzmann_constant 5.670374419e-8
#define gas_constant_R 8.3144598
//#define Faraday_constant_F 9.648533212e4 //=eNA
#define Avogadro_constant 6.02214076e23
// math
#define Chaos_costant 4.6692016
#ifndef Pi
#define Pi 3.1415926535897932384626433832795
#endif
#define mathematical_constant_e 2.71828182845904523536028747135266249775724709369995
#define golden_ratio 1.6180339887498948482045868343656

//-------------------------------------------------------------------------------------------------//
// divation define 最终运行完后寻找的分子分母
const double EPS = 1e-15; // double 的误差控制,print_find_EPS存在的原因，找这个参数的值找了我一个下午
// #define uper 7.194727e+077
// #define lower 8.904174e+023 //final line of sorted buffer gen
#define uper 1.327004e+057
#define lower 1.642296e+003 // final line of unsorted buffer gen
//-------------------------------------------------------------------------------------------------//
// Control
#define Target_diva_point 1e-13 // 3.42e-14
#define Target_diva_map_max 1e-9//1e-10
#define Target_diva_map_min 1e-10//1e-17
#define Target_diva_debug 9.861436e-010 // 9.861434e-010
#define All_pass_start 0                // 8250000//分段时开始计算偏移的数组头，legacy parameter
#define All_pass_end i1_t[power_length - 1] / 3
// 二选一
#define all_pass
//#define debug // final step

// 二选一
// #define my_sort
#define my_qsort

// Choose target diva method三选一
// #define point
#define map
// #define debug_point倒数第二步

// #define print_buffer_before_sort
// #define print_buffer_before_shrink
// #define print_buffer_after_shrink
// #define print_buffer_zero
// #define print_find_EPS
//--------------------------------------全局变量----------------------------------------------//
unsigned long long count = 0;       // 删掉后剩下的数据
unsigned long long count_del = 0;   // 删掉的重复数据
unsigned long long local_count = 0; // 在指定diva中的个数
clock_t start_time;                 // 开始的时间
unsigned long long q_left = 0, q_right; // delete
#ifdef multi_thread
#include <pthread.h>
#define core_count 8
pthread_t th[core_count];                       // 设定的线程数
#define all_work_group 3652745460               // 373621248
double *buffer_original, *buffer_original_save; // 原始数组
double *buffer_o_thread[core_count];            // 每个线程的数组指针
long long total_pushed_thread[core_count];      // 数组排序删前每个线程的数组个数
int total_pushed = 0;                           // 所有线程的生成个数之和
double *buffer_shrink, *buffer_shrink_save;     // 删除后留下的数组
#endif
#ifndef multi_thread
#define max1 3652745460LL                       // buffer_original
double buffer_original; // 原始数组
double buffer_shrink;     // 删除后留下的数组
unsigned long long total_pushed = 0;            // 数组排序删前的个数

#endif
// double stack[] = {
//     Planck_length, Planck_mass, Planck_time, Planck_constant,
//     Speed_of_light, Charge, Avogadro_constant, Gravitational_constant, Boltzmann_constant,
//     Pi, Chaos_costant, mathematical_constant_e, golden_ratio, Vacuum_Permittivity_E0,
//     Proton_length, Proton_mass, Stefan_Boltzmann_constant, gas_constant_R
//     ,Planck_constant_reduced, Vacuum_Permittivity_u0
//     ,Coulomb_constant_F, Conductance_quantum, Wien_constant
// };//the original stack
double stack[] = {
    Planck_length, Planck_mass, Planck_time, Planck_constant,
    Charge, Avogadro_constant, Gravitational_constant, Boltzmann_constant,
    Pi, Chaos_costant, mathematical_constant_e, golden_ratio, Vacuum_Permittivity_E0,
    Proton_length, Proton_mass, Stefan_Boltzmann_constant
    ,Planck_constant_reduced, Vacuum_Permittivity_u0
    ,Coulomb_constant_F, Conductance_quantum, Wien_constant
};//after first round of 2 similar, delete speed of light and gas constant is more practical.
int length_ele; // how to calculate : printf("%d\n",sizeof(stack) / sizeof(stack[0]));
int length_ele_extended;
//--------------------------------------用户函数--------------------------------------------//
//void quicksort(int left, int right, double *buffer);

double calculate_divation(double result)
{
    return result / Target_number - 1;
}

void print_time(clock_t func_time)
{
    clock_t end_time;
    end_time = clock();
    printf("%lf\n", (double)(end_time - func_time) / CLOCKS_PER_SEC);
}
//---------------------------------------MAIN---------------------------------------------//
int main(void)
{
    //strange result
    double A = Speed_of_light*powl(2*Pi*Gravitational_constant*Gravitational_constant*Vacuum_Permittivity_E0,-0.5);
    double B = Avogadro_constant;
    printf("%e %e diva = %e\n",A,B,(A-B)/B);

    printf("Started\n");
    start_time = clock();
    length_ele = sizeof(stack) / sizeof(stack[0]);
    length_ele_extended = sizeof(stack) / sizeof(stack[0]) * 5;
    printf("length_ele = %d length_ele_extended = %d\n", length_ele, length_ele_extended);//符合定义的函数组
//--------------------------------single_thread_gen-----------------------------------------//
    long long i, j;
    int k, l, m, o;
    double s1, s2, s3, s4, s5, s6;
    double stack_extended[length_ele_extended];

    for (i = 0; i < length_ele; i++)
    {
        stack_extended[i + 0 * length_ele] = stack[i];
        stack_extended[i + 1 * length_ele] = powl(stack[i], -0.5);
        stack_extended[i + 2 * length_ele] = powl(stack[i], 0.5);
        stack_extended[i + 3 * length_ele] = powl(stack[i], 1.5);
        stack_extended[i + 4 * length_ele] = powl(stack[i], 2);
    }
//-------------------------------new_single_thread_gen---------------------------------------//
    for (i = 0; i < length_ele_extended; i++) //两个相乘的关系
    {
        for (j = i + 1; j < length_ele_extended; j++)
            if(i % length_ele != j % length_ele)//相同效果
            for (l = 0; l < length_ele_extended; l++)
                if(j % length_ele != l % length_ele)//相同效果
                {
                    buffer_original = stack_extended[i] * stack_extended[j];
                    //if (i % length_ele != j % length_ele & j % length_ele != l % length_ele)//相同效果
                    if (buffer_original >= stack_extended[l] * 0.999999 & buffer_original <= stack_extended[l] * 1.0000001)
                    {
                        printf("2 in a row\n");
                        printf("i == %d j == %d l == %d\n", i, j, l);
                        printf("A_buffer == %e B_buffer == %e D_buffer == %e\n",
                            stack_extended[i], stack_extended[j], stack_extended[l]);
                        printf("*buffer_original == %e count == %d", buffer_original, total_pushed);
                        printf("\n\n");
                        total_pushed++;
                    }
                }
    }
    printf("2##########################i= %lld\n", total_pushed);
    //wrong way if(i != 0 & j != 54 & k != 59) if(i != 2 & j != 33 & k != 38) if(i != 8 & j != 16 & k != 19) if (i != 50 & j != 58 & k != 61)
    total_pushed = 0;
    for (i = 0; i < length_ele_extended; i++) // 三个相乘的关系
        for (j = i + 1; j < length_ele_extended; j++)
            if(i % length_ele != j % length_ele)//相同效果
            for (k = j + 1; k < length_ele_extended; k++)
                if(j % length_ele != k % length_ele)//相同效果
                if(i == 0 & j == 54 & k == 59) break; 
                else if(i == 2 & j == 33 & k == 38) break; 
                else if(i == 8 & j == 16 & k == 19) break; 
                else if(i == 50 & j == 58 & k == 61) break; 
                else
                for (l = 0; l < length_ele_extended; l++)
                    if(k % length_ele != l % length_ele)//相同效果
                    {
                        if((k % length_ele != l % length_ele) & (j % length_ele != l % length_ele) & (i % length_ele != l % length_ele))//^0.5and ^2
                        {
                            buffer_shrink = stack_extended[i] * stack_extended[j] * stack_extended[k];
                            if (buffer_shrink >= stack_extended[l] * 0.9999999 & buffer_shrink <= stack_extended[l] * 1.000001)
                            {
                                printf("3 in a row\n");
                                printf("i == %d j == %d k == %d l == %d\n", i, j, k, l);
                                printf("A_buffer == %e B_buffer == %e C_buffer == %e D_buffer == %e\n",
                                    stack_extended[i], stack_extended[j], stack_extended[k], stack_extended[l]);
                                printf("*buffer_shrink == %e count == %d",buffer_shrink,total_pushed);
                                printf("\n\n");
                                total_pushed++;
                            }
                        }
                    }
    printf("3##########################i= %lld\n", total_pushed);
    //if(j != 2 & k != 33 & l != 38) if(j != 8 & k != 16 & l != 19) if (j != 50 & k != 58 & l != 61)
    total_pushed = 0;
    for (i = 0; i < length_ele_extended; i++) // 三个相乘的关系
        for (j = i + 1; j < length_ele_extended; j++)
            if(i % length_ele != j % length_ele)//274174891324147123481//单相互不够
            for (k = j + 1; k < length_ele_extended; k++)
                if(i % length_ele != k % length_ele)
                if(j % length_ele != k % length_ele)
                if(i == 0 & j == 54 & k == 59) break; else if(i == 2 & j == 33 & k == 38) break; 
                else if(i == 8 & j == 16 & k == 19) break; else if(i == 50 & j == 58 & k == 61) break; 
                else
                for (l = k + 1; l < length_ele_extended; l++)
                    if(i % length_ele != l % length_ele)
                    if(j % length_ele != l % length_ele)
                    if(k % length_ele != l % length_ele)
                    if(i == 0 & k == 54 & l == 59) break; else if(i == 2 & k == 33 & l == 38) break; 
                    else if(i == 8 & k == 16 & l == 19) break; else if(i == 50 & k == 58 & l == 61) break; 
                    else if(j == 2 & k == 33 & l == 38) break; else if(j == 8 & k == 16 & l == 19) break;
                    else if(j == 50 & k == 58 & l == 6) break;
                    //delete 4
                    else if(i == 3 & j == 29 & k == 54 & l == 60) break;
                    else if(i == 5 & j == 45 & k == 54 & l == 58) break;
                    else if(i == 16 & j == 33 & k == 39 & l == 50) break;
                    else if(i == 21 & j == 54 & k == 59 & l == 63) break;
                    else if(i == 23 & j == 27 & k == 42 & l == 58) break;
                    else if(i == 23 & j == 33 & k == 38 & l == 65) break;
                    else
                    for (m = 0; m < length_ele_extended; m++)
                        if(i % length_ele != m % length_ele)
                        if(j % length_ele != m % length_ele)
                        if(k % length_ele != m % length_ele)
                        if(l % length_ele != m % length_ele)
                        {
                            if((k % length_ele != m % length_ele) & (j % length_ele != m % length_ele) & (i % length_ele != m % length_ele))//^0.5and ^2
                            {
                                buffer_shrink = stack_extended[i] * stack_extended[j] * stack_extended[k] * stack_extended[l];
                                if (buffer_shrink >= stack_extended[m] * 0.9999999 & buffer_shrink <= stack_extended[m] * 1.000001)
                                {
                                    printf("4 in a row\n");
                                    printf("i == %d j == %d k == %d l == %d m == %d\n", i, j, k, l, m);
                                    printf("A_buffer == %e B_buffer == %e C_buffer == %e D_buffer == %e Target == %e\n",
                                        stack_extended[i], stack_extended[j], stack_extended[k], stack_extended[l],stack_extended[m]);
                                    printf("*buffer_shrink == %e count == %d",buffer_shrink,total_pushed);
                                    printf("\n\n");
                                    total_pushed++;
                                }
                            }
                        }
    printf("4##########################i= %lld\n", total_pushed);
    total_pushed = 0;
    for (i = 0; i < length_ele_extended; i++) // 三个相乘的关系
        for (j = i + 1; j < length_ele_extended; j++)
            if(i % length_ele != j % length_ele)//  防止同一常数在单一表达式内重复出现
            for (k = j + 1; k < length_ele_extended; k++)
                if(i % length_ele != k % length_ele)
                if(j % length_ele != k % length_ele)
                if(i == 0 & j == 54 & k == 59) break; else if(i == 2 & j == 33 & k == 38) break; 
                else if(i == 8 & j == 16 & k == 19) break; else if(i == 50 & j == 58 & k == 61) break; 
                else
                for (l = k + 1; l < length_ele_extended; l++)
                    if(i % length_ele != l % length_ele)
                    if(j % length_ele != l % length_ele)
                    if(k % length_ele != l % length_ele)
                    if(i == 0 & k == 54 & l == 59) break; else if(i == 2 & k == 33 & l == 38) break; 
                    else if(i == 8 & k == 16 & l == 19) break; else if(i == 50 & k == 58 & l == 61) break; 
                    else if(j == 2 & k == 33 & l == 38) break; else if(j == 8 & k == 16 & l == 19) break;
                    else if(j == 50 & k == 58 & l == 6) break;
                    //delete 4
                    else if(i == 3 & j == 29 & k == 54 & l == 60) break;
                    else if(i == 5 & j == 45 & k == 54 & l == 58) break;
                    else if(i == 16 & j == 33 & k == 39 & l == 50) break;
                    else if(i == 21 & j == 54 & k == 59 & l == 63) break;
                    else if(i == 23 & j == 27 & k == 42 & l == 58) break;
                    else if(i == 23 & j == 33 & k == 38 & l == 65) break;
                    else
                    for (m = l + 1; m < length_ele_extended; m++)
                        if(i % length_ele != m % length_ele)
                        if(j % length_ele != m % length_ele)
                        if(k % length_ele != m % length_ele)
                        if(l % length_ele != m % length_ele)
                        if(i == 0 & l == 54 & m == 59) break;
                        else if(i == 2 & l == 33 & m == 38) break;
                        else if(i == 8 & l == 16 & m == 19) break;
                        else if(i == 50 & l == 58 & m == 61)break;
                        else if(j == 2 & l == 33 & m == 38) break;
                        else if(j == 8 & l == 16 & m == 19) break;
                        else if(j == 50 & l == 58 & m == 61)break;
                        else if(k == 2 & l == 33 & m == 38) break;
                        else if(k == 8 & l == 16 & m == 19) break;
                        else if(k == 50 & l == 58 & m == 61)break;
                        //delete 4
                        else if(i == 3  & k == 29 & l == 54 & m == 60) break;
                        else if(i == 5  & k == 45 & l == 54 & m == 58) break;
                        else if(i == 16 & k == 33 & l == 39 & m == 50) break;
                        else if(i == 21 & k == 54 & l == 59 & m == 63) break;
                        else if(i == 23 & k == 27 & l == 42 & m == 58) break;
                        else if(i == 23 & k == 33 & l == 38 & m == 65) break;
                        else if(j == 3  & k == 29 & l == 54 & m == 60) break;
                        else if(j == 5  & k == 45 & l == 54 & m == 58) break;
                        else if(j == 16 & k == 33 & l == 39 & m == 50) break;
                        else if(j == 21 & k == 54 & l == 59 & m == 63) break;
                        else if(j == 23 & k == 27 & l == 42 & m == 58) break;
                        else if(j == 23 & k == 33 & l == 38 & m == 65) break;
                        //delete 5 
                        else if(i == 3 & j == 19 & k == 50 & l == 54 & m == 60) break;
                        else if(i == 3 & j == 37 & k == 54 & l == 60 & m == 61) break;
                        else if(i == 4 & j == 5 & k == 28 & l == 50 & m == 85) break;
                        else if(i == 5 & j == 6 & k == 12 & l == 37 & m == 45) break;
                        else if(i == 5 & j == 6 & k == 12 & l == 37 & m == 59) break;
                        else if(i == 5 & j == 6 & k == 12 & l == 45 & m == 59) break;
                        else if(i == 5 & j == 24 & k == 39 & l == 50 & m == 79) break;
                        else if(i == 5 & j == 39 & k == 42 & l == 57 & m == 75) break;
                        else if(i == 11 & j == 27 & k == 39 & l == 50 & m == 85) break;
                        else if(i == 15 & j == 32 & k == 38 & l == 69 & m == 94) break;
                        else if(i == 53 & j == 61 & k == 62 & l == 72 & m == 75) break;
                        else
                        for (o = 0; o < length_ele_extended; o++)
                            if(i % length_ele != o % length_ele)
                            if(j % length_ele != o % length_ele)
                            if(k % length_ele != o % length_ele)
                            if(l % length_ele != o % length_ele)
                            if(m % length_ele != o % length_ele)
                            {
                                if((l % length_ele != m % length_ele) & (k % length_ele != m % length_ele) & (j % length_ele != m % length_ele) & (i % length_ele != m % length_ele))//^0.5and ^2
                                {
                                    //3
                                    // buffer_shrink = stack_extended[i] * stack_extended[j] * stack_extended[k];
                                    // if (buffer_shrink >= stack_extended[o] * 0.9999999 & buffer_shrink <= stack_extended[o] * 1.000001)
                                    // {
                                    //     printf("3 in a row\n");
                                    //     printf("i == %d j == %d k == %d o == %d\n", i, j, k, o);
                                    //     printf("A_buffer == %e B_buffer == %e C_buffer == %e D_buffer == %e\n",
                                    //         stack_extended[i], stack_extended[j], stack_extended[k], stack_extended[o]);
                                    //     printf("*buffer_shrink == %e count == %d",buffer_shrink,total_pushed);
                                    //     printf("\n\n");
                                    //     total_pushed++;
                                    //     o = length_ele_extended;
                                    // }
                                    // //4
                                    // buffer_shrink = stack_extended[i] * stack_extended[j] * stack_extended[k] * stack_extended[l];
                                    // if (buffer_shrink >= stack_extended[o] * 0.9999999 & buffer_shrink <= stack_extended[o] * 1.000001)
                                    // {
                                    //     printf("4 in a row\n");
                                    //     printf("i == %d j == %d k == %d l == %d o == %d\n", i, j, k, l, o);
                                    //     printf("A_buffer == %e B_buffer == %e C_buffer == %e D_buffer == %e Target == %e\n",
                                    //         stack_extended[i], stack_extended[j], stack_extended[k], stack_extended[l],stack_extended[o]);
                                    //     printf("*buffer_shrink == %e count == %d",buffer_shrink,total_pushed);
                                    //     printf("\n\n");
                                    //     total_pushed++;
                                    //     l++;//will ruin //5
                                    // }
                                    //5
                                    buffer_shrink = stack_extended[i] * stack_extended[j] * stack_extended[k] * stack_extended[l] * stack_extended[m];
                                    if (buffer_shrink >= stack_extended[o] * 0.9999999 & buffer_shrink <= stack_extended[o] * 1.000001)
                                    {
                                        //printf("5 in a row\n");
                                        printf("else if(i == %d & j == %d & k == %d & l == %d & m == %d) break;\n", i, j, k, l, m);
                                        // printf("i == %d j == %d k == %d l == %d m == %d\n", i, j, k, l, m);
                                        // printf( "o == %d\n", o);
                                        // printf("A_buffer == %e B_buffer == %e C_buffer == %e D_buffer == %e E_buffer == %e Target == %e\n",
                                        //     stack_extended[i], stack_extended[j], stack_extended[k], stack_extended[l],stack_extended[m],stack_extended[o]);
                                        // printf("*buffer_shrink == %e count == %d",buffer_shrink,total_pushed);
                                        // printf("\n\n");
                                        total_pushed++;
                                    }
                                }
                            }
    printf("5##########################i= %lld\n", total_pushed);
    printf("End time\n");
    print_time(start_time);
    system("pause");
    return 0;
}
